name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Configure and Build
        run: |
          cd static_link_project
          mkdir build
          cd build        
          cmake ..
          make

      - name: Run Tests
        run: |
          cd static_link_project/build
          ./main.out
          ctest --output-on-failure
